import { test } from "node:test";
import assert from "node:assert";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { checkBody, stampBody, stripMarker, computeSha, splitBody, composeBody, BEGIN_MARKER } from "./body-marker.mjs";

const CLI_PATH = fileURLToPath(new URL("./body-marker.mjs", import.meta.url));

const AT = "2026-08-23T04:12:31Z";

test("stamp した本文は sha_matches になる", () => {
  const stamped = stampBody("採点失敗時の 50 埋めをやめた。", AT);
  const r = checkBody(stamped);
  assert.strictEqual(r.has_marker, true);
  assert.strictEqual(r.sha_matches, true);
  assert.strictEqual(r.last_ai_edit, AT);
});

test("本文を 1 文字変えると sha_matches が false になる", () => {
  const stamped = stampBody("採点失敗時の 50 埋めをやめた。", AT);
  const edited = stamped.replace("やめた", "やめました");
  assert.strictEqual(checkBody(edited).sha_matches, false);
});

test("マーカーが無い本文は has_marker が false", () => {
  const r = checkBody("人間が手で書いた本文。");
  assert.strictEqual(r.has_marker, false);
  assert.strictEqual(r.sha_matches, false);
});

test("マーカーが 2 つある本文は人間が触った扱いにする", () => {
  const stamped = stampBody("本文。", AT);
  const doubled = stamped + "<!-- pr-desc: sha=aaaaaa last-ai-edit=" + AT + " -->\n";
  const r = checkBody(doubled);
  assert.strictEqual(r.has_marker, true);
  assert.strictEqual(r.sha_matches, false);
});

test("行末空白と CRLF の揺れでは sha_matches が壊れない", () => {
  const stamped = stampBody("本文。", AT);
  const noisy = stamped.replace(/\n/g, "  \r\n");
  assert.strictEqual(checkBody(noisy).sha_matches, true);
});

test("stripMarker はマーカー行だけを落とす", () => {
  const stamped = stampBody("本文。", AT);
  assert.strictEqual(stripMarker(stamped), "本文。\n");
});

test("computeSha は 12 桁の 16 進を返す", () => {
  assert.match(computeSha("abc"), /^[0-9a-f]{12}$/);
});

test("stamp を 2 回かけてもマーカーは 1 つだけ", () => {
  const once = stampBody("本文。", AT);
  const twice = stampBody(once, AT);
  assert.strictEqual((twice.match(/pr-desc: sha=/g) || []).length, 1);
  assert.strictEqual((twice.match(/pr-desc:begin/g) || []).length, 1);
  assert.strictEqual(checkBody(twice).sha_matches, true);
});

test("マーカーより後に署名が足されても sha_matches は保たれる", () => {
  const stamped = stampBody("本文。", AT);
  const withFooter = stamped + "\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n";
  assert.strictEqual(checkBody(withFooter).sha_matches, true);
});

test("マーカーより前に人間が足した文は sha_matches を false にする", () => {
  const stamped = stampBody("本文。", AT);
  const edited = stamped.replace("本文。", "本文。\n\n人間の加筆。");
  assert.strictEqual(checkBody(edited).sha_matches, false);
});

// マーカーより後の追記は検知しない。投稿先が本文末尾に署名を自動で足すため、
// そこを照合対象から外している。人間の加筆はマーカーより前に入るのが通常。
test("マーカーより後の人間の加筆は検知しない（既知の穴）", () => {
  const stamped = stampBody("本文。", AT);
  const appended = stamped + "\n人間が一番下に足した文。\n";
  assert.strictEqual(checkBody(appended).sha_matches, true);
});

test("印が無い本文は no_marker で、全部が囲みの上になる", () => {
  const r = splitBody("人間が手で書いた本文。");
  assert.strictEqual(r.state, "no_marker");
  assert.strictEqual(r.above, "人間が手で書いた本文。\n");
  assert.strictEqual(r.inside, "");
  assert.strictEqual(r.below, "");
});

test("印が無い本文に組み立てると、元の本文が残り区切り線の下に囲みができる", () => {
  const out = composeBody("人間が書いた本文。", "スキルが書いた本文。", "", AT);
  assert.match(out, /^人間が書いた本文。\n\n---\n\n<!-- pr-desc:begin -->\nスキルが書いた本文。\n<!-- pr-desc: sha=[0-9a-f]{12} last-ai-edit=.+ -->\n$/);
});

test("囲みの上が空なら区切り線を置かない", () => {
  const out = composeBody("", "スキルが書いた本文。", "", AT);
  assert.ok(!out.includes("---"));
  assert.ok(out.startsWith(BEGIN_MARKER));
});

test("組み立てた本文を切り分けると matches で、上と中が元に戻る", () => {
  const out = composeBody("人間が書いた本文。", "スキルが書いた本文。", "", AT);
  const r = splitBody(out);
  assert.strictEqual(r.state, "matches");
  assert.strictEqual(r.above, "人間が書いた本文。\n");
  assert.strictEqual(r.inside, "スキルが書いた本文。\n");
  assert.strictEqual(r.last_ai_edit, AT);
});

test("何度組み立て直しても区切り線が増えない", () => {
  const once = composeBody("人間が書いた本文。", "1 回目。", "", AT);
  const a = splitBody(once);
  const twice = composeBody(a.above, "2 回目。", a.below, AT);
  const b = splitBody(twice);
  const thrice = composeBody(b.above, "3 回目。", b.below, AT);
  assert.strictEqual((thrice.match(/^---$/gm) || []).length, 1);
  assert.strictEqual(splitBody(thrice).state, "matches");
  assert.strictEqual(splitBody(thrice).inside, "3 回目。\n");
});

test("囲みの中だけを書き換えると mismatch になり、上と下は取り出せる", () => {
  const out = composeBody("人間が書いた本文。", "スキルが書いた本文。", "", AT);
  const edited = out.replace("スキルが書いた本文。", "人間が手直しした本文。");
  const r = splitBody(edited);
  assert.strictEqual(r.state, "mismatch");
  assert.strictEqual(r.above, "人間が書いた本文。\n");
  assert.strictEqual(r.inside, "人間が手直しした本文。\n");
});

test("囲みの上を書き換えても matches のまま", () => {
  const out = composeBody("人間が書いた本文。", "スキルが書いた本文。", "", AT);
  const edited = out.replace("人間が書いた本文。", "人間が書き直した本文。");
  const r = splitBody(edited);
  assert.strictEqual(r.state, "matches");
  assert.strictEqual(r.above, "人間が書き直した本文。\n");
});

test("囲みの下に署名が足されても matches のまま、下として取り出せる", () => {
  const out = composeBody("", "スキルが書いた本文。", "", AT);
  const withFooter = out + "\n_Generated by [Claude Code](https://claude.ai/code)_\n";
  const r = splitBody(withFooter);
  assert.strictEqual(r.state, "matches");
  assert.strictEqual(r.below, "_Generated by [Claude Code](https://claude.ai/code)_\n");
});

test("旧い形（終了の印だけ）で中身が一致する本文は matches になり、全部が囲みの中になる", () => {
  const legacy = "旧い形の本文。\n<!-- pr-desc: sha=" + computeSha("旧い形の本文。\n") + " last-ai-edit=" + AT + " -->\n";
  const r = splitBody(legacy);
  assert.strictEqual(r.state, "matches");
  assert.strictEqual(r.above, "");
  assert.strictEqual(r.inside, "旧い形の本文。\n");
});

test("旧い形で中身が一致しない本文は mismatch になる", () => {
  const legacy = "旧い形の本文。\n<!-- pr-desc: sha=aaaaaaaaaaaa last-ai-edit=" + AT + " -->\n";
  assert.strictEqual(splitBody(legacy).state, "mismatch");
});

test("旧い形の本文を組み立て直すと新しい形の囲みになる", () => {
  const legacy = "旧い形の本文。\n<!-- pr-desc: sha=" + computeSha("旧い形の本文。\n") + " last-ai-edit=" + AT + " -->\n";
  const r = splitBody(legacy);
  const out = composeBody(r.above, "新しい本文。", r.below, AT);
  assert.ok(out.startsWith(BEGIN_MARKER));
  assert.ok(!out.includes("---"));
  assert.strictEqual(splitBody(out).state, "matches");
});

test("開始の印が 2 つある本文は mismatch", () => {
  const out = composeBody("", "本文。", "", AT);
  assert.strictEqual(splitBody(BEGIN_MARKER + "\n" + out).state, "mismatch");
});

test("開始の印だけあって終了の印が無い本文は mismatch", () => {
  assert.strictEqual(splitBody(BEGIN_MARKER + "\n本文。\n").state, "mismatch");
});

test("終了の印が開始の印より前にある本文は mismatch", () => {
  const end = "<!-- pr-desc: sha=aaaaaaaaaaaa last-ai-edit=" + AT + " -->";
  assert.strictEqual(splitBody(end + "\n" + BEGIN_MARKER + "\n本文。\n").state, "mismatch");
});

test("本文が空のときは区切り線を置かず囲みだけになる", () => {
  const out = composeBody("", "本文。", "", AT);
  assert.ok(out.startsWith(BEGIN_MARKER));
  assert.strictEqual((out.match(/^---$/gm) || []).length, 0);
});

test("stripMarker は開始の印も終了の印も落とす", () => {
  const out = composeBody("", "本文。", "", AT);
  assert.strictEqual(stripMarker(out), "本文。\n");
});

// CLI の引数処理そのものを検証する。純粋関数のテストではカバーできない
// 「--overwrite のとき --body-file を読まない」という分岐を確かめるため、
// 実プロセスとして起動する（他のテストからの唯一の例外）。
test("CLI: compose --overwrite は存在しない --body-file でも成功する", () => {
  const dir = mkdtempSync(join(tmpdir(), "body-marker-test-"));
  const newBodyFile = join(dir, "new-body.md");
  const missingBodyFile = join(dir, "current-body.md");
  writeFileSync(newBodyFile, "新しい本文。\n");
  assert.strictEqual(existsSync(missingBodyFile), false);

  const out = execFileSync(
    process.execPath,
    [CLI_PATH, "compose", "--overwrite", "--body-file", missingBodyFile, "--new-body-file", newBodyFile, "--at", AT],
    { encoding: "utf8" },
  );

  assert.strictEqual(existsSync(missingBodyFile), false);
  const r = splitBody(out);
  assert.strictEqual(r.state, "matches");
  assert.strictEqual(r.above, "");
  assert.strictEqual(r.inside, "新しい本文。\n");
});

test("CLI: --overwrite の無い compose は --body-file を読み、既存本文が残る", () => {
  const dir = mkdtempSync(join(tmpdir(), "body-marker-test-"));
  const newBodyFile = join(dir, "new-body.md");
  const bodyFile = join(dir, "current-body.md");
  writeFileSync(newBodyFile, "新しい本文。\n");
  writeFileSync(bodyFile, "既存の本文（人間が書いた）。\n");

  const out = execFileSync(
    process.execPath,
    [CLI_PATH, "compose", "--body-file", bodyFile, "--new-body-file", newBodyFile, "--at", AT],
    { encoding: "utf8" },
  );

  const r = splitBody(out);
  assert.strictEqual(r.state, "matches");
  assert.strictEqual(r.above, "既存の本文（人間が書いた）。\n");
  assert.strictEqual(r.inside, "新しい本文。\n");
});

test("CLI: --body-file が存在しないと --overwrite 無しではエラーになる（読む経路の確認）", () => {
  const dir = mkdtempSync(join(tmpdir(), "body-marker-test-"));
  const newBodyFile = join(dir, "new-body.md");
  const missingBodyFile = join(dir, "current-body.md");
  writeFileSync(newBodyFile, "新しい本文。\n");

  assert.throws(() => {
    execFileSync(
      process.execPath,
      [CLI_PATH, "compose", "--body-file", missingBodyFile, "--new-body-file", newBodyFile, "--at", AT],
      { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
    );
  }, /ENOENT/);
});

test("終了の印が 2 つあり 1 つ目より上に文章がある本文は broken になる", () => {
  const out = composeBody("", "スキルが書いた本文。", "", AT);
  const pasted = "人間が書いた段落。\n" + out + "<!-- pr-desc: sha=aaaaaaaaaaaa last-ai-edit=" + AT + " -->\n";
  const r = splitBody(pasted);
  assert.strictEqual(r.state, "mismatch");
  assert.strictEqual(r.broken, true);
});

test("終了の印が開始の印より前にある本文は broken になる", () => {
  const end = "<!-- pr-desc: sha=aaaaaaaaaaaa last-ai-edit=" + AT + " -->";
  const r = splitBody(end + "\n" + BEGIN_MARKER + "\n本文。\n");
  assert.strictEqual(r.state, "mismatch");
  assert.strictEqual(r.broken, true);
});

test("開始の印だけあって終了の印が無い本文は broken になる", () => {
  const r = splitBody(BEGIN_MARKER + "\n本文。\n");
  assert.strictEqual(r.state, "mismatch");
  assert.strictEqual(r.broken, true);
});

test("中身が印と合わないだけの mismatch は broken にならない", () => {
  const out = composeBody("人間が書いた本文。", "スキルが書いた本文。", "署名。", AT);
  const edited = out.replace("スキルが書いた本文。", "人間が手直しした本文。");
  const r = splitBody(edited);
  assert.strictEqual(r.state, "mismatch");
  assert.strictEqual(r.broken, false);
  assert.strictEqual(r.above, "人間が書いた本文。\n");
  assert.strictEqual(r.below, "署名。\n");
});

test("印が揃っている本文は broken が false", () => {
  const r = splitBody(composeBody("", "本文。", "", AT));
  assert.strictEqual(r.state, "matches");
  assert.strictEqual(r.broken, false);
});

test("印が無い本文は broken が false", () => {
  const r = splitBody("人間が手で書いた本文。\n");
  assert.strictEqual(r.state, "no_marker");
  assert.strictEqual(r.broken, false);
});

test("mismatch でも終了の印から読めた日時を保持する", () => {
  const out = composeBody("", "スキルが書いた本文。", "", AT);
  const edited = out.replace("スキルが書いた本文。", "人間が手直しした本文。");
  const r = splitBody(edited);
  assert.strictEqual(r.state, "mismatch");
  assert.strictEqual(r.last_ai_edit, AT);
  assert.strictEqual(checkBody(edited).last_ai_edit, AT);
});

test("state サブコマンドの出力に broken が入る", () => {
  const dir = mkdtempSync(join(tmpdir(), "body-marker-test-"));
  const bodyFile = join(dir, "current-body.md");
  writeFileSync(bodyFile, BEGIN_MARKER + "\n本文。\n");

  const out = execFileSync(process.execPath, [CLI_PATH, "state", "--body-file", bodyFile], { encoding: "utf8" });
  const r = JSON.parse(out);
  assert.strictEqual(r.state, "mismatch");
  assert.strictEqual(r.broken, true);
});

test("囲みの下が空でない本文の compose → split → compose で上下が保たれ区切り線は 1 本のまま", () => {
  const first = composeBody("人間が書いた本文。", "スキルが書いた本文。", "_署名_", AT);
  assert.strictEqual((first.match(/^---$/gm) || []).length, 1);

  const r1 = splitBody(first);
  assert.strictEqual(r1.state, "matches");
  assert.strictEqual(r1.above, "人間が書いた本文。\n");
  assert.strictEqual(r1.below, "_署名_\n");

  const second = composeBody(r1.above, "2 回目の本文。", r1.below, AT);
  assert.strictEqual((second.match(/^---$/gm) || []).length, 1);

  const r2 = splitBody(second);
  assert.strictEqual(r2.state, "matches");
  assert.strictEqual(r2.above, "人間が書いた本文。\n");
  assert.strictEqual(r2.inside, "2 回目の本文。\n");
  assert.strictEqual(r2.below, "_署名_\n");
});

test("broken な本文を上下ごと丸ごと置き換えると印が 1 組だけになる", () => {
  const out = composeBody("", "スキルが書いた本文。", "", AT);
  const pasted = "人間が書いた段落。\n" + out + "<!-- pr-desc: sha=aaaaaaaaaaaa last-ai-edit=" + AT + " -->\n";
  assert.strictEqual(splitBody(pasted).broken, true);

  const rebuilt = composeBody("", "新しい本文。", "", AT);
  const r = splitBody(rebuilt);
  assert.strictEqual(r.state, "matches");
  assert.strictEqual(r.broken, false);
  assert.strictEqual(r.inside, "新しい本文。\n");
  assert.strictEqual((rebuilt.match(/pr-desc: sha=/g) || []).length, 1);
  assert.strictEqual((rebuilt.match(/pr-desc:begin/g) || []).length, 1);
});

test("broken な本文を上下を保ったまま組み立て直すと印が増えたままになる（だから丸ごと置き換える）", () => {
  const end = "<!-- pr-desc: sha=aaaaaaaaaaaa last-ai-edit=" + AT + " -->";
  const reversed = end + "\n" + BEGIN_MARKER + "\n本文。\n";
  const r = splitBody(reversed);
  assert.strictEqual(r.broken, true);

  const rebuilt = composeBody(r.above, "新しい本文。", r.below, AT);
  assert.strictEqual(splitBody(rebuilt).state, "mismatch");
  assert.strictEqual(splitBody(rebuilt).broken, true);
});
